[package]
name = "officer_velvet"
version = "0.1.0"
authors = ["Aurorans Solis <primalucegd@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
chrono = "0.4.19"
crossbeam-channel = "0.5.0"
rand = "0.7.3"
serde = "1.0.117"
serde_json = "1.0.59"
structopt = "0.3.20"

[dependencies.tokio]
version = "0.2"
features = ["fs", "macros", "signal", "time"]

[dependencies.serenity]
version = "0.9.0"
features = ["cache", "framework", "rustls_backend", "standard_framework"]

# [patch.crates-io]
# openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }